/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taketwo;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import taketwo.model.Waypoint;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        final var file = "../waypoints.json";
        try {
            ObjectMapper mapper0 =
                    new ObjectMapper().configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
            CollectionType listType =
                    mapper0.getTypeFactory().constructCollectionType(ArrayList.class, Waypoint.class);
            ArrayList<Waypoint> rowsArrayList =
                    mapper0.readValue(new File(file), listType);
            System.out.println("Loaded " + rowsArrayList.size() + " waypoints");

            var state = (new Waypoint(null, 1d, 2d)).process(rowsArrayList);
            System.out.println("======================\nInsurance report\n" + state);
        } catch (IOException e) {
            System.out.println("Failed to parse file: " + e);
        }
    }
}
